services:
  mariadb:
    container_name: mariadb
    env_file:
      - ../.env
    build: ./requirements/mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD_FILE: /run/secrets/mysql_admin_password
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_admin_password
      - mysql_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    env_file:
      - ../.env
    build: ./requirements/wordpress
    image: wordpress:latest
    environment:
      PHP_FPM_PORT: ${PHP_FPM_PORT:-9000}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wordpress_admin_password
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wordpress_user_password
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_URL: ${WORDPRESS_URL}
    secrets:
      - mysql_password
      - wordpress_admin_password
      - wordpress_user_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    env_file:
      - ../.env
    build: ./requirements/nginx
    image: nginx:latest
    environment:
      PHP_FPM_PORT: ${PHP_FPM_PORT:-9000}
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rmamisoa/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rmamisoa/data/wordpress

networks:
  inception_network:
    driver: bridge

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_admin_password:
    file: ../secrets/mysql_admin_password.txt
  mysql_password:
    file: ../secrets/mysql_password.txt
  wordpress_admin_password:
    file: ../secrets/wordpress_admin_password.txt
  wordpress_user_password:
    file: ../secrets/wordpress_user_password.txt
